In [21]:
import numpy as np


In [22]:
print(np.__version__)


1.21.5


In [23]:
a = np.array(3)
a

array(3)

In [24]:
one_dimmesion_array = np.array([1,2,3,4,5,6,7,8,9])
one_dimmesion_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
first_array = np.array([1,2,3])
first_array

array([1, 2, 3])

In [26]:
secound_array = np.array([[1,2,3],[4,5,6]])
secound_array

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
third_array = np.array ([[[1,2,3],[4,5,6],[7,8,9]]])
third_array

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [28]:
print (first_array.ndim)
print (secound_array.ndim)
print (third_array.ndim)


1
2
3


In [29]:
third_array.ndim

3

In [30]:
lets_check = np.array ([1,2,3,4,5,6])
lets_check[0:3]

array([1, 2, 3])

In [31]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])



7


In [32]:
print(lets_check[2] + lets_check [5])


9


In [33]:
two_dimmession_array = np.array([[1,2,3],[4,5,6]])


In [35]:
# Access array , 
two_dimmession_array [0 , 2]



3

In [37]:
two_dimmession_array [1, 2]


6

In [40]:
import numpy as np

third = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(third[0, 1, 2])



6


In [42]:
third_array = np.array ([[[1, 2, 3 ], [4, 5, 6 ]], [[7, 8, 9, ], [10, 11, 12]]])



In [44]:
print (third_array [0, 1, 1 ])


5


In [47]:
third_array [1, 0, 2 ]


9

In [48]:
third_array [1, 1, 2]

12

In [52]:
lets_check_dtype = np.array ([1,2,3,4,5,6,7,8,9])
lets_check_dtype.dtype

dtype('int64')

In [53]:
name = np.array (["Steve Jobs", "Bill Gates", "Mark Zukerberg"])
name

array(['Steve Jobs', 'Bill Gates', 'Mark Zukerberg'], dtype='<U14')

In [54]:
name.dtype

dtype('<U14')