In [ ]:
import numpy as np


In [ ]:
print(np.__version__)


1.21.5


In [ ]:
a = np.array(3)
a

array(3)

In [ ]:
one_dimmesion_array = np.array([1,2,3,4,5,6,7,8,9])
one_dimmesion_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
first_array = np.array([1,2,3])
first_array

array([1, 2, 3])

In [ ]:
secound_array = np.array([[1,2,3],[4,5,6]])
secound_array

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
third_array = np.array ([[[1,2,3],[4,5,6],[7,8,9]]])
third_array

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [ ]:
print (first_array.ndim)
print (secound_array.ndim)
print (third_array.ndim)


1
2
3


In [ ]:
third_array.ndim

3

In [ ]:
lets_check = np.array ([1,2,3,4,5,6])
lets_check[0:3]

array([1, 2, 3])

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])



7


In [ ]:
print(lets_check[2] + lets_check [5])


9


In [ ]:
two_dimmession_array = np.array([[1,2,3],[4,5,6]])


In [ ]:
# Access array , 
two_dimmession_array [0 , 2]



3

In [ ]:
two_dimmession_array [1, 2]


6

In [ ]:
import numpy as np

third = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(third[0, 1, 2])



6


In [ ]:
third_array = np.array ([[[1, 2, 3 ], [4, 5, 6 ]], [[7, 8, 9, ], [10, 11, 12]]])



In [ ]:
print (third_array [0, 1, 1 ])


5


In [ ]:
third_array [1, 0, 2 ]


9

In [ ]:
third_array [1, 1, 2]

12

In [ ]:
lets_check_dtype = np.array ([1,2,3,4,5,6,7,8,9])
lets_check_dtype.dtype

dtype('int64')

In [ ]:
name = np.array (["Steve Jobs", "Bill Gates", "Mark Zukerberg"])
name

array(['Steve Jobs', 'Bill Gates', 'Mark Zukerberg'], dtype='<U14')

In [ ]:
name.dtype

dtype('<U14')

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
lets_learn_copy_function = np.array ([1,2,3,4,5,6])
copy_array = lets_learn_copy_function.copy()
print(lets_learn_copy_function)
print(copy_array)





[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [ ]:
lets_learn_copy_function[0] = 32
lets_learn_copy_function


array([32,  2,  3,  4,  5,  6])

In [ ]:
copy_array

array([1, 2, 3, 4, 5, 6])

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
first = np.array ([1, 2, 3])
view_functon_apply = first.view()
first

array([1, 2, 3])

In [ ]:
view_functon_apply

array([1, 2, 3])

In [ ]:
first [0] = 32

In [ ]:
first

array([32,  2,  3])

In [ ]:
view_functon_apply

array([32,  2,  3])

In [ ]:
first [2] = 33

In [ ]:
first

array([32,  2, 33])

In [ ]:
view_functon_apply

array([32,  2, 33])

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)


[[[[[1 2 3 4]]]]]


In [ ]:
shape_function_learn = np.array ([1 , 2 , 3, 4, 5 , 6 , 7, 8, 9, 10, 11, 12])
shape_function_learn

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
shape_function_learn.reshape(4 , 3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
from numpy import random

x = random.randint(300)

print(x)

221


In [ ]:
generate_randome_number = random.randint(200)
generate_randome_number

191

In [ ]:
generate_flot_random_number = random.rand()
generate_flot_random_number

0.22523262465859162

In [ ]:
x=random.randint(100, size=(5))

print(x)


[54 15 21 54 95]


In [ ]:
new_array = random.randint (30, size = (3))
new_array

array([29, 10, 22])

In [ ]:
new_array

array([29, 10, 22])

In [ ]:
from matplotlib.image import imread

panda = imread('/work/panda.png')
print(type(panda))

<class 'numpy.ndarray'>


In [ ]:
dog_image = imread ("dog-photo.png")
dog_image

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]],

       [[0.69411767, 0.8039216 , 0.8862745 , 1.        ],
        [0.7019608 , 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49411765, 0.68235296, 0.84313726, 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ]],

       [[0.6901961 , 0.8       , 0.88235295, 1.        ],
        [0.69803923, 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49803922, 0.686274

In [ ]:
dog_image[10]


array([[0.75686276, 0.827451  , 0.8901961 , 1.        ],
       [0.7294118 , 0.8156863 , 0.8862745 , 1.        ],
       [0.7254902 , 0.8156863 , 0.8862745 , 1.        ],
       ...,
       [0.5254902 , 0.7058824 , 0.85882354, 1.        ],
       [0.5176471 , 0.7019608 , 0.85882354, 1.        ],
       [0.5254902 , 0.7058824 , 0.8509804 , 1.        ]], dtype=float32)

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=9cc8d813-6f1a-4174-b3e8-966d835d6140' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>